#ifndef _ROBOT_BOARD_PC_H_
#define _ROBOT_BOARD_PC_H_

#define ROBOT_PLATFORM ROBOT_PLATFORM_PC
#define ROBOT_BOARD ROBOT_BOARD_PC


#define ROBOT_NEOPIXEL_COUNT 16
#define ROBOT_HAVE_RC 1
#define ROBOT_HAVE_MPU 0
#define ROBOT_HAVE_ROBOTCONTROL_MPU 0

#endif

