#ifndef _ROBOT_BOARD_BEAGLEBONE_BLUE_H_
#define _ROBOT_BOARD_BEAGLEBONE_BLUE_H_

#define ROBOT_PLATFORM ROBOT_PLATFORM_BEAGLEBONE
#define ROBOT_BOARD ROBOT_BOARD_BEAGLEBONE_BLUE

#define ROBOT_HAVE_RC 1
#define ROBOT_HAVE_BALANCE 1
#define ROBOT_HAVE_IMU 1
#define ROBOT_HAVE_BATTERY 1
#define ROBOT_HAVE_ROBOTCONTROL_MPU 1
#define ROBOT_HAVE_ROBOTCONTROL_BATTERY 1
#define ROBOT_NEOPIXEL_COUNT RC_EXT_NEOPIXEL_COUNT


#endif
