#ifndef _ROBOT_BOARD_BEAGLEBONE_POCKET_H_
#define _ROBOT_BOARD_BEAGLEBONE_POCKET_H_

#define ROBOT_PLATFORM ROBOT_PLATFORM_BEAGLEBONE
#define ROBOT_BOARD ROBOT_BOARD_BEAGLEBONE_POCKET

#define ROBOT_HAVE_RC 1
/* #define ROBOT_HAVE_BALANCE */
/* #define ROBOT_HAVE_MPU */
/* #define ROBOT_HAVE_ROBOTCONTROL_MPU */
/* #define ROBOT_HAVE_WIFI */
#define ROBOT_NEOPIXEL_COUNT RC_EXT_NEOPIXEL_COUNT


#endif
